language: php

sudo: required

services:
  - docker

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install
  - cp phpunit.xml.dist phpunit.xml
  - docker network create eodm-network
  - if [[ ! `docker network ls | grep eodm-network` ]]; then docker network create eodm-network; fi
  - docker-compose up -d --build

script:
  - composer ci
